version: '3.8'
services:
  app:
    container_name: CloudPortFolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    environment:
      - MONGODB_URI=mongodb://database:27017/userData
      - TZ=America/Toronto
    depends_on:
      database:
        condition: service_healthy
    restart: always

  database:
    container_name: mongodb-server
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    volumes:
      - ./userData:/data/db
    environment:
      - MONGO_INITDB_DATABASE=userData
      - TZ=America/Toronto
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand(\"ping\").ok'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: always

networks:
  default:
    driver: bridge